name: service
description: A sample command-line application.
version: 1.0.0

publish_to: none

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
#   path: ^1.8.0
  async: ^2.9.0
  grpc: ^3.0.2

  proto:
    path: ../proto/



dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
